version: "3"

services:
  web:
    build: 
      context: . # 指定 docker compose資料夾位置
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app